version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: sidekiq_alive
    versions:
    - 2.0.4
    - 2.0.5
  - dependency-name: rails
    versions:
    - 6.1.3
    - 6.1.3.1
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: mock_redis
    versions:
    - 0.27.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
  - dependency-name: dotenv-rails
    versions:
    - 2.7.6
  - dependency-name: rubocop-rspec
    versions:
    - 1.41.0
  - dependency-name: factory_bot
    versions:
    - 6.1.0
